src/blogs/urls.py
from django.urls import path
from .views import (
                        BlogListView,
                        BlogDetailSlugView,
                    )
app_name = "blogs"
urlpatterns = [
    path('', BlogListView.as_view(), name="list"),
    path('<slug:slug>/', BlogDetailSlugView.as_view(), name="detail" ),

]

src/ecommerce_project/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path,include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from carts.views import cart_home, cart_detail_api_view
from billing.views import payment_method_view
from accounts.views import LoginView, RegisterView, guest_register_view
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from .views import home_page, contact_page, project_page

urlpatterns = [
    path('', home_page, name="home"),
    path('accounts/', RedirectView.as_view(url='/account')),
    path('account/', include("accounts.urls", namespace='accounts')),
    path('contact/', contact_page, name="contact"),
    path('project/', project_page, name="project"),
    path('login/', LoginView.as_view(), name="login"),
    path('register/guest/', guest_register_view, name="guest_register"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', RegisterView.as_view(), name="register"),
    path('blogs/', include("blogs.urls", namespace="blogs")),
    path('products/', include("products.urls", namespace='products')),
    path('search/', include("search.urls", namespace='search')),
    path('cart/', include("carts.urls", namespace='cart')),
    path('api/cart/', cart_detail_api_view, name="api-cart"),
    path('billing/payment-method/', payment_method_view, name="payment-method-view"),
    path('checkout/address/create', checkout_address_create_view, name="checkout_address_create"),
    path('checkout/address/reuse', checkout_address_reuse_view, name="checkout_address_reuse_view"),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
     urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
     urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/base/common_banner.html
<!-- Start Banner Area -->
<section class="banner-area organic-breadcrumb">
  <div class="container">
    <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
      <div class="col-first">
        <h1>{{ title }}</h1>
        <nav class="d-flex align-items-center">
          <a href="{% url 'home' %}">Home<span class="lnr lnr-arrow-right"></span></a>
          <a href="#">{{ page_title }}</a>
        </nav>
      </div>
    </div>
  </div>
</section>
<!-- End Banner Area -->

src/templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" href="{% static "css/linearicons.css" %}">
<link rel="stylesheet" href="{% static "fontawesome/font-awesome.min.css" %}">
<!-- <link rel="stylesheet" href="{% static "css/style.css" %}"> -->
<link rel="stylesheet" href="{% static "css/jquery-confirm.css" %}">
<link rel="stylesheet" href="{% static "css/themify-icons.css" %} ">
<link rel="stylesheet" href="{% static "css/owl.carousel.css" %} ">
<link rel="stylesheet" href="{% static "css/nice-select.css" %} ">
<link rel="stylesheet" href="{% static "css/nouislider.min.css" %} ">
<link rel="stylesheet" href="{% static "css/ion.rangeSlider.css" %} ">
<link rel="stylesheet" href="{% static "css/ion.rangeSlider.skinFlat.css" %} ">
<link rel="stylesheet" href="{% static "css/magnific-popup.css" %} ">
<link rel="stylesheet" href="{% static "css/main.css" %} ">

src/templates/base/footer.html
{% load static %}

	<!-- start footer Area -->
	<footer class="footer-area section_gap">
		<div class="container">
			<div class="row">
				<div class="col-lg-3  col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6>About Us</h6>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore dolore
							magna aliqua.
						</p>
					</div>
				</div>
				<div class="col-lg-4  col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6>Newsletter</h6>
						<p>Stay update with our latest</p>
						<div class="" id="mc_embed_signup">

							<form target="_blank" novalidate="true" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
							 method="get" class="form-inline">

								<div class="d-flex flex-row">

									<input class="form-control" name="EMAIL" placeholder="Enter Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '"
									 required="" type="email">


									<button class="click-btn btn btn-default"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></button>
									<div style="position: absolute; left: -5000px;">
										<input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
									</div>

									<!-- <div class="col-lg-4 col-md-4">
												<button class="bb-btn btn"><span class="lnr lnr-arrow-right"></span></button>
											</div>  -->
								</div>
								<div class="info"></div>
							</form>
						</div>
					</div>
				</div>
				<div class="col-lg-3  col-md-6 col-sm-6">
					<div class="single-footer-widget mail-chimp">
						<h6 class="mb-20">Instragram Feed</h6>
						<ul class="instafeed d-flex flex-wrap">
							<li><img src="{% static 'img/i1.jpg' %}" alt=""></li>
							<li><img src="{% static 'img/i2.jpg' %}" alt=""></li>
							<li><img src="{% static 'img/i3.jpg' %}" alt=""></li>
							<li><img src="{% static 'img/i4.jpg' %}" alt=""></li>
							<li><img src="{% static 'img/i5.jpg' %}" alt=""></li>
							<li><img src="{% static 'img/i6.jpg' %}" alt=""></li>
							<li><img src="{% static 'img/i7.jpg' %}" alt=""></li>
							<li><img src="{% static 'img/i8.jpg' %}" alt=""></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-2 col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6>Follow Us</h6>
						<p>Let us be social</p>
						<div class="footer-social d-flex align-items-center">
							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
							<a href="#"><i class="fa fa-dribbble"></i></a>
							<a href="#"><i class="fa fa-behance"></i></a>
						</div>
					</div>
				</div>
			</div>

		</div>
	</footer>
	<!-- End footer Area -->

src/templates/base/js.html
{% load static %}
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="https://js.stripe.com/v3/"></script>
<script src="{% static 'js/jquery-confirm.js' %}"></script>
<script src="{% static 'js/csrf.ajax.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static "js/jquery.ajaxchimp.min.js" %} "></script>
<script src="{% static "js/jquery.nice-select.min.js" %} "></script>
<script src="{% static "js/jquery.sticky.js" %} "></script>
<script src="{% static "js/nouislider.min.js" %} "></script>
<script src="{% static "js/countdown.js" %} "></script>
<script src="{% static "js/jquery.magnific-popup.min.js" %} "></script>
<script src="{% static "js/owl.carousel.min.js" %} "></script>
<!--gmaps Js-->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
<script src="{% static "js/gmaps.min.js" %} "></script>
<script src="{% static "js/main.js" %} "></script>
<script src="{% static "js/custom.js" %} "></script>

src/templates/base/navbar.html
{% load static %}
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'blogs:list' as blog_list_url %}
{% url 'products:list' as products_list_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'accounts:home' as account_url %}
{% url 'register' as register_url %}
{% url 'cart:home' as cart_url %}

	<header class="header_area sticky-header">
		<div class="main_menu">
			<nav class="navbar navbar-expand-lg navbar-light main_box">
				<div class="container">
					<!-- Brand and toggle get grouped for better mobile display -->
					<a class="navbar-brand logo_h" href="{{ home_url }}"><img src="{% static 'img/logo.png' %}" alt=""></a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
					 aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse offset" id="navbarSupportedContent">
						<ul class="nav navbar-nav menu_nav ml-auto">
							<li class="nav-item {% if request.path == home_url %}active {% endif %}">
                <a class="nav-link" href="{{ home_url }}">Home  <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item {% if request.path == products_list_url %}active {% endif %}">
                <a class="nav-link" href="{{ products_list_url }}">Products</a>
              </li>
							<!-- <li class="nav-item submenu dropdown">
								<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
								 aria-expanded="false">Shop</a>
								<ul class="dropdown-menu">
									<li class="nav-item"><a class="nav-link" href="category.html">Shop Category</a></li>
									<li class="nav-item"><a class="nav-link" href="single-product.html">Product Details</a></li>
									<li class="nav-item"><a class="nav-link" href="checkout.html">Product Checkout</a></li>
									<li class="nav-item"><a class="nav-link" href="cart.html">Shopping Cart</a></li>
									<li class="nav-item"><a class="nav-link" href="confirmation.html">Confirmation</a></li>
								</ul>
							</li> -->

							<li class="nav-item {% if request.path == blog_list_url %}active {% endif %}">
								<a class="nav-link" href="{{ blog_list_url }}">Blog</a>
							</li>
              {% if request.user.is_authenticated %}
							<li class="nav-item submenu dropdown">
								<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
								 aria-expanded="false">Account</a>
								<ul class="dropdown-menu">
									<li class="nav-item {% if request.path == account_url %}active {% endif %}">
										<a class="nav-link" href="{{ account_url }}">Home</a>
									</li>
									<!-- <li class="nav-item"><a class="nav-link" href="single-blog.html">Blog Details</a></li> -->
									<li class="nav-item {% if request.path == logout_url %}active {% endif %}">
										<a class="nav-link" href="{{ logout_url }}">Logout</a>
									</li>
								</ul>
							</li>
              {% else %}
              <li class="nav-item {% if request.path == register_url %}active {% endif %}">
                <a class="nav-link" href="{{ register_url }}">Register</a>
              </li>
              <li class="nav-item {% if request.path == login_url %}active {% endif %}">
                <a class="nav-link" href="{{ login_url }}">Login</a>
              </li>
              {% endif %}
							<!-- <li class="nav-item submenu dropdown">
								<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
								 aria-expanded="false">Pages</a>
								<ul class="dropdown-menu">
									<li class="nav-item"><a class="nav-link" href="login.html">Login</a></li>
								</ul>
							</li> -->
              <li class="nav-item {% if request.path == contact_url %}active {% endif %}">
                <a class="nav-link" href="{{ contact_url }}">Contact</a>
              </li>

						</ul>
						<ul class="nav navbar-nav navbar-right">
							<li class="nav-item {% if request.path == cart_url %}active {% endif %}">
			          <a class="cart" href="{{ cart_url }}"><span class="navbar-cart-count">{{ request.session.cart_items }}</span> <i class="ti-bag"></i> </a>
			        </li>
							<li class="nav-item">
								<button class="search"><span class="lnr lnr-magnifier" id="search"></span></button>
							</li>
						</ul>
					</div>
				</div>
			</nav>
		</div>
		<div class="search_input" id="search_input_box">
			<div class="container">
        {% include 'search/snippets/search-form.html' %}
			</div>
		</div>
	</header>
	<!-- End Header Area -->