src/blogs/urls.py
from django.urls import path
from .views import (
                        BlogListView,
                        BlogDetailSlugView,
                    )
app_name = "blogs"
urlpatterns = [
    path('', BlogListView.as_view(), name="list"),
    path('<slug:slug>/', BlogDetailSlugView.as_view(), name="detail" ),

]

src/carts/urls.py
from django.urls import path
from .views import (
                    cart_home,
                    cart_update,
                    checkout_home,
                    checkout_done_view,
                    )
app_name = "carts"
urlpatterns = [
    path('', cart_home, name="home"),
    path('checkout/success/', checkout_done_view, name="success" ),
    path('update/', cart_update, name="update" ),
    path('checkout/', checkout_home, name="checkout" ),

]

src/ecommerce_project/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path,include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from carts.views import cart_home, cart_detail_api_view
from billing.views import payment_method_view
from accounts.views import LoginView, RegisterView, guest_register_view
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from .views import home_page, contact_page, project_page

urlpatterns = [
    path('', home_page, name="home"),
    path('accounts/', RedirectView.as_view(url='/account')),
    path('account/', include("accounts.urls", namespace='accounts')),
    path('contact/', contact_page, name="contact"),
    path('project/', project_page, name="project"),
    path('login/', LoginView.as_view(), name="login"),
    path('register/guest/', guest_register_view, name="guest_register"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', RegisterView.as_view(), name="register"),
    path('blogs/', include("blogs.urls", namespace="blogs")),
    path('products/', include("products.urls", namespace='products')),
    path('search/', include("search.urls", namespace='search')),
    path('cart/', include("carts.urls", namespace='cart')),
    path('api/cart/', cart_detail_api_view, name="api-cart"),
    path('billing/payment-method/', payment_method_view, name="payment-method-view"),
    path('checkout/address/create', checkout_address_create_view, name="checkout_address_create"),
    path('checkout/address/reuse', checkout_address_reuse_view, name="checkout_address_reuse_view"),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
     urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
     urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/carts/models.py
from decimal import Decimal
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save, m2m_changed
from products.models import Product

User = settings.AUTH_USER_MODEL

class CartManager(models.Manager):

    def new_or_get(self, request):
        cart_id = request.session.get('cart_id', None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = self.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)

class Cart(models.Model):
    user        = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    products    = models.ManyToManyField(Product, blank=True)
    subtotal    = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total       = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    updated     = models.DateTimeField(auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)


def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        # print(total)
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()

m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)

def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = Decimal(instance.subtotal) + Decimal(10)
    else:
        instance.total = 0.00

pre_save.connect(pre_save_cart_receiver, sender=Cart)

src/carts/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from accounts.forms import LoginForm, GuestForm
from accounts.models import GuestEmail
from addresses.forms import AddressForm
from addresses.models import Address
from billing.models import BillingProfile
from products.models import Product
from .models import Cart
from orders.models import Order

def cart_detail_api_view(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    products = [{
                "id": x.id,
                "url": x.get_absolute_url(),
                "image": x.image.url,
                "name": x.name,
                "price": x.price,
                }
                for x in cart_obj.products.all()]
    cart_data = {"products": products, "subtotal": cart_obj.subtotal, "total": cart_obj.total}
    return JsonResponse(cart_data)

def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    return render(request, "carts/home.html", {"cart": cart_obj})

def cart_update(request):
    product_id = request.POST.get('product_id')

    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except:
            print('Show message to user, product is gone')
            return redirect("cart:home")
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
            added = False
        else:
            cart_obj.products.add(product_obj)
            added = True
        request.session['cart_items'] = cart_obj.products.count()
        # return redirect(product_obj.get_absolute_url())
        if request.is_ajax():
            print("ajax Request")
            json_data = {
                "added"         : added,
                "removed"       : not added,
                "cartItemCount" : cart_obj.products.count()
            }
            return JsonResponse(json_data)
    return redirect("cart:home")

def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0:
        return redirect("cart:home")

    login_form = LoginForm()
    guest_form = GuestForm()
    address_form = AddressForm()
    billing_address_id = request.session.get("billing_address_id", None)
    shipping_address_id = request.session.get("shipping_address_id", None)
    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
    address_qs = None
    if billing_profile is not None:
        if request.user.is_authenticated:
            address_qs = Address.objects.filter(billing_profile=billing_profile)
        # shipping_address_qs     = address_qs.filter(address_type='shipping')
        # billing_address_qs      = address_qs.filter(address_type='billing')
        order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)
        if shipping_address_id:
            order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
            del request.session["shipping_address_id"]
        if billing_address_id:
            order_obj.billing_address = Address.objects.get(id=billing_address_id)
            del request.session["billing_address_id"]
        if billing_address_id or shipping_address_id:
            order_obj.save()

    if request.method == "POST":
        "check that order is done"
        is_done = order_obj.check_done()
        if is_done:
            order_obj.mark_paid()
            request.session['cart_items'] = 0
            del request.session['cart_id']
            return redirect("cart:success")

    context = {
        "object"                : order_obj,
        "billing_profile"       : billing_profile,
        'login_form'            : login_form,
        'guest_form'            : guest_form,
        'address_form'          : address_form,
        "address_qs"            : address_qs,
    }
    return render(request, "carts/checkout.html", context)

def checkout_done_view(request):
    return render(request, "carts/checkout-done.html", {})

src/carts/templates/carts/checkout-done.html
{% extends 'base.html' %}

{% block content %}
{% include 'base/common_banner.html' with title='Thankyou' page_title='Thankyou' %}

<section>
  <div class="container">
    <div class="row">
      <div class="mx-auto py-5 text-center">
        <h1 class="display-1">Thankyou For Your Order</h1>
      </div>
    </div>
  </div>
</section>
{% endblock %}

src/carts/templates/carts/checkout.html
{% extends 'base.html' %}

{% block content %}
{% include 'base/common_banner.html' with title='Shipping Address' page_title='Shipping' %}
<section class="section_gap">
  <div class="container">
    <div class="row">
      {% if not billing_profile %}
       <div class="col-12 col-md-6">
         <p class="lead">Login</p>
         {% include 'accounts/snippets/form.html' with form=login_form next_url=request.build_absolute_uri %}
       </div>
       <div class="col-12 col-md-6">
         <p class="lead">Continue as Guest</p>
         {% url "guest_register" as guest_register_url %}
         {% include 'accounts/snippets/form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url %}
       </div>
      {% else %}
        {% if not object.shipping_address %}
          <div class="col-12">
            <p class="lead">Shipping Address</p>
            <hr>
          </div>
          <div class="col-12">
            {% url "checkout_address_create" as checkout_address_create_url %}
            {% include 'addresses/snippets/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create_url address_type='shipping' %}
          </div>
          {% url 'checkout_address_reuse_view' as checkout_address_reuse %}
          {% include 'addresses/prev_add.html' with address_qs=address_qs next_url=request.build_absolute_uri address_type='shipping' action_url=checkout_address_reuse %}
        {% elif not object.billing_address %}
          <div class="col-12">
            <p class="lead">Billing Address</p>
            <hr>
          </div>
          <div class="col-6">
            {% url "checkout_address_create" as checkout_address_create_url %}
            {% include 'addresses/snippets/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create_url address_type='billing' %}
          </div>
          {% url 'checkout_address_reuse_view' as checkout_address_reuse %}
          {% include 'addresses/prev_add.html' with address_qs=address_qs next_url=request.build_absolute_uri address_type='billing' action_url=checkout_address_reuse %}
        {% else %}
          <div class="col-12">
            <h1>Finalize Checkout</h1>
            <p>Cart Items: {% for product in object.carts.products.all %}{{ product }}
              {% if not forloop.last %}, {% endif %}{% endfor %}
            </p>
            <p>Shipping Address: {{ object.shipping_address.get_address }}</p>
            <p>Billing Address: {{ object.billing_address.get_address }}</p>
            <p>Cart Total : {{ object.carts.total }}</p>
            <p>Shipping Total : {{ object.shipping_total }}</p>
            <p>Order Total : {{ object.total }}</p>
            <form class="" action="" method="post">
              {% csrf_token %}
              <button type="submit" name="button" class="btn btn-success">Checkout</button>
            </form>
          </div>
        {% endif %}
      {% endif %}
    </div>
  </div>
</section>
{% endblock %}

src/carts/templates/carts/home.html
{% extends 'base.html' %}
{% block content %}
{% include 'base/common_banner.html' with title='Shopping Cart' page_title='Cart' %}
  <section class="cart_area">
    <div class="container">
      <div class="cart_inner">
        {% if cart.products.exists %}
        <div class="table-responsive">
          <table class="table cart-table">
            <thead>
              <tr>
                <th>S no.</th>
                <th>Product Image</th>
                <th>Product Name</th>
                <th>Product Price</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody class="cart-body">
              {% for product in cart.products.all %}
              <tr class="cart-product">
                <td scope="row">{{ forloop.counter }}</td>
                <td>
                  {% if product.image %}
                  <img src="{{ product.image.url }}" alt="" class="img-fluid" style="width:100px;height:100px;">
                  {% endif %}
                </td>
                <td><a href="{{ product.get_absolute_url }}" class="cart-product-name">{{ product.title }}</a></td>
                <td><h5>{{ product.price }}</h5></td>
                <td>{% include 'carts/snippets/remove-product.html' with product_id=product.id %}</td>
              </tr>
              {% endfor %}
              <tr>
                <td colspan="3"></td>
                <td><h5>Subtotal</h5></td>
                <td><h5 class="cart-subtotal">{{ cart.subtotal }}</h5></td>
              </tr>
              <tr>
                <td colspan="3"></td>
                <td><h5>Total</h5></td>
                <td><h5 class="cart-total">{{ cart.total }}</h5</td>
              </tr>
              <tr>
                <td colspan="4">
                  <a href="{% url 'products:list' %}" class="btn gray_btn">Continue Shopping</a>
                </td>
                <td>
                  <a href="{% url 'cart:checkout' %}" class="btn primary-btn">Checkout</a>
                </td>
              </tr>
            </tbody>
          </table>
          <div class="cart-item-remove-form" style="display:none">
            {% include 'carts/snippets/remove-product.html' %}
          </div>
        </div>
        <div class="my-2">
        </div>
        {% else %}
        <p class="lead">Cart is empty</p>
        {% endif %}
      </div>
    </div>
  </section>
{% endblock %}
<!--================Cart Area =================-->
    <section class="cart_area">
        <div class="container">
            <div class="cart_inner">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Product</th>
                                <th scope="col">Price</th>
                                <th scope="col">Quantity</th>
                                <th scope="col">Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    <div class="media">
                                        <div class="d-flex">
                                            <img src="img/cart.jpg" alt="">
                                        </div>
                                        <div class="media-body">
                                            <p>Minimalistic shop for multipurpose use</p>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <h5>$360.00</h5>
                                </td>
                                <td>
                                    <div class="product_count">
                                        <input type="text" name="qty" id="sst" maxlength="12" value="1" title="Quantity:"
                                            class="input-text qty">
                                        <button onclick="var result = document.getElementById('sst'); var sst = result.value; if( !isNaN( sst )) result.value++;return false;"
                                            class="increase items-count" type="button"><i class="lnr lnr-chevron-up"></i></button>
                                        <button onclick="var result = document.getElementById('sst'); var sst = result.value; if( !isNaN( sst ) &amp;&amp; sst > 0 ) result.value--;return false;"
                                            class="reduced items-count" type="button"><i class="lnr lnr-chevron-down"></i></button>
                                    </div>
                                </td>
                                <td>
                                    <h5>$720.00</h5>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="media">
                                        <div class="d-flex">
                                            <img src="img/cart.jpg" alt="">
                                        </div>
                                        <div class="media-body">
                                            <p>Minimalistic shop for multipurpose use</p>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <h5>$360.00</h5>
                                </td>
                                <td>
                                    <div class="product_count">
                                        <input type="text" name="qty" id="sst" maxlength="12" value="1" title="Quantity:"
                                            class="input-text qty">
                                        <button onclick="var result = document.getElementById('sst'); var sst = result.value; if( !isNaN( sst )) result.value++;return false;"
                                            class="increase items-count" type="button"><i class="lnr lnr-chevron-up"></i></button>
                                        <button onclick="var result = document.getElementById('sst'); var sst = result.value; if( !isNaN( sst ) &amp;&amp; sst > 0 ) result.value--;return false;"
                                            class="reduced items-count" type="button"><i class="lnr lnr-chevron-down"></i></button>
                                    </div>
                                </td>
                                <td>
                                    <h5>$720.00</h5>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="media">
                                        <div class="d-flex">
                                            <img src="img/cart.jpg" alt="">
                                        </div>
                                        <div class="media-body">
                                            <p>Minimalistic shop for multipurpose use</p>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <h5>$360.00</h5>
                                </td>
                                <td>
                                    <div class="product_count">
                                        <input type="text" name="qty" id="sst" maxlength="12" value="1" title="Quantity:"
                                            class="input-text qty">
                                        <button onclick="var result = document.getElementById('sst'); var sst = result.value; if( !isNaN( sst )) result.value++;return false;"
                                            class="increase items-count" type="button"><i class="lnr lnr-chevron-up"></i></button>
                                        <button onclick="var result = document.getElementById('sst'); var sst = result.value; if( !isNaN( sst ) &amp;&amp; sst > 0 ) result.value--;return false;"
                                            class="reduced items-count" type="button"><i class="lnr lnr-chevron-down"></i></button>
                                    </div>
                                </td>
                                <td>
                                    <h5>$720.00</h5>
                                </td>
                            </tr>
                            <tr class="bottom_button">
                                <td>
                                    <a class="gray_btn" href="#">Update Cart</a>
                                </td>
                                <td>

                                </td>
                                <td>

                                </td>
                                <td>
                                    <div class="cupon_text d-flex align-items-center">
                                        <input type="text" placeholder="Coupon Code">
                                        <a class="primary-btn" href="#">Apply</a>
                                        <a class="gray_btn" href="#">Close Coupon</a>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>

                                </td>
                                <td>

                                </td>
                                <td>
                                    <h5>Subtotal</h5>
                                </td>
                                <td>
                                    <h5>$2160.00</h5>
                                </td>
                            </tr>
                            <tr class="shipping_area">
                                <td>

                                </td>
                                <td>

                                </td>
                                <td>
                                    <h5>Shipping</h5>
                                </td>
                                <td>
                                    <div class="shipping_box">
                                        <ul class="list">
                                            <li><a href="#">Flat Rate: $5.00</a></li>
                                            <li><a href="#">Free Shipping</a></li>
                                            <li><a href="#">Flat Rate: $10.00</a></li>
                                            <li class="active"><a href="#">Local Delivery: $2.00</a></li>
                                        </ul>
                                        <h6>Calculate Shipping <i class="fa fa-caret-down" aria-hidden="true"></i></h6>
                                        <select class="shipping_select">
                                            <option value="1">Bangladesh</option>
                                            <option value="2">India</option>
                                            <option value="4">Pakistan</option>
                                        </select>
                                        <select class="shipping_select">
                                            <option value="1">Select a State</option>
                                            <option value="2">Select a State</option>
                                            <option value="4">Select a State</option>
                                        </select>
                                        <input type="text" placeholder="Postcode/Zipcode">
                                        <a class="gray_btn" href="#">Update Details</a>
                                    </div>
                                </td>
                            </tr>
                            <tr class="out_button_area">
                                <td>

                                </td>
                                <td>

                                </td>
                                <td>

                                </td>
                                <td>
                                    <div class="checkout_btn_inner d-flex align-items-center">
                                        <a class="gray_btn" href="#">Continue Shopping</a>
                                        <a class="primary-btn" href="#">Proceed to checkout</a>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
    <!--================End Cart Area =================-->